name: Upload Assets

on:
  release:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python3.8 -m pip install "rdflib~=5.0"
    - name: Build Assets
      run: |
        python3.8 make-tsv.py > cili.tsv
        xz -z cili.tsv
    - name: Upload
      run: |
        tag_name="${GITHUB_REF##*/}"
        gh release upload "${GITHUB_REF##*/}" cili.tsv.xz#CILI inventory and definitions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

